import pygame

GAME_WINDOW_WIDTH = 1024
GAME_WINDOW_HEIGHT = 768

CUBE_SIZE = 96

COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 100, 100)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_YELLOW = (255, 255, 51)
COLOR_ORANGE = (255, 178, 80)
COLOR_PURPLE = (255, 102, 255)
COLOR_GRAY = (172, 172, 172)

STANDING = 0
DOWN_LEFT = 1
DOWN_RIGHT = 2
UP_LEFT = 3
UP_RIGHT = 4
FALLING = 5
LEFT_SPIN = 6
RIGHT_SPIN = 7

START = 0
PLAYING = 1
GAME_OVER = 2
ONE_SECOND_PAUSE = 3

FONT_SIZE = 36

PATH_IMAGE_START_PAGE = 'images/startpage.png'

PATH_IMAGE_PLAYER_LEFT_DOWN = 'images/playerleftdown.png'
PATH_IMAGE_PLAYER_RIGHT_DOWN = 'images/playerrightdown.png'
PATH_IMAGE_PLAYER_LEFT_UP = 'images/playerleftup.png'
PATH_IMAGE_PLAYER_RIGHT_UP = 'images/playerrightup.png'
PATH_IMAGE_PLAYER_LITTLE = 'images/playerlittle.png'
PATH_IMAGE_PLAYER_LEFT_DOWN_JUMP = 'images/playerleftdownjump.png'
PATH_IMAGE_PLAYER_RIGHT_DOWN_JUMP = 'images/playerrightdownjump.png'
PATH_IMAGE_PLAYER_LEFT_UP_JUMP = 'images/playerleftupjump.png'
PATH_IMAGE_PLAYER_RIGHT_UP_JUMP = 'images/playerrightupjump.png'
PATH_IMAGE_PLAYER_SPIN_1 = 'images/spin1.png'
PATH_IMAGE_PLAYER_SPIN_2 = 'images/spin2.png'

PATH_IMAGE_QBERT_LOSES = 'images/qbertloses.png'

PATH_IMAGE_RED_BALL = 'images/redEnemyBall.png'
PATH_IMAGE_PURPLE_BALL = 'images/purpleEnemyBall.png'
PATH_IMAGE_COILY_LEFT = 'images/coilyleft.png'
PATH_IMAGE_COILY_RIGHT = 'images/coilyright.png'
PATH_IMAGE_COILY_LEFT_JUMP = 'images/coilyleftjump.png'
PATH_IMAGE_COILY_RIGHT_JUMP = 'images/coilyrightjump.png'

PATH_IMAGE_DISK = 'images/disk.png'
PATH_IMAGE_SWEAR = 'images/swear.png'

IMAGE_START_PAGE = pygame.image.load(PATH_IMAGE_START_PAGE)

IMAGE_PLAYER_LEFT_DOWN = pygame.image.load(PATH_IMAGE_PLAYER_LEFT_DOWN)
IMAGE_PLAYER_RIGHT_DOWN = pygame.image.load(PATH_IMAGE_PLAYER_RIGHT_DOWN)
IMAGE_PLAYER_LEFT_UP = pygame.image.load(PATH_IMAGE_PLAYER_LEFT_UP)
IMAGE_PLAYER_RIGHT_UP = pygame.image.load(PATH_IMAGE_PLAYER_RIGHT_UP)
IMAGE_PLAYER_LEFT_DOWN_JUMP = pygame.image.load(PATH_IMAGE_PLAYER_LEFT_DOWN_JUMP)
IMAGE_PLAYER_RIGHT_DOWN_JUMP = pygame.image.load(PATH_IMAGE_PLAYER_RIGHT_DOWN_JUMP)
IMAGE_PLAYER_LEFT_UP_JUMP = pygame.image.load(PATH_IMAGE_PLAYER_LEFT_UP_JUMP)
IMAGE_PLAYER_RIGHT_UP_JUMP = pygame.image.load(PATH_IMAGE_PLAYER_RIGHT_UP_JUMP)
IMAGE_PLAYER_LITTLE = pygame.image.load(PATH_IMAGE_PLAYER_LITTLE)
IMAGE_PLAYER_SPIN_1 = pygame.image.load(PATH_IMAGE_PLAYER_SPIN_1)
IMAGE_PLAYER_SPIN_2 = pygame.image.load(PATH_IMAGE_PLAYER_SPIN_2)
IMAGE_PLAYER_SPINS = [IMAGE_PLAYER_SPIN_1, IMAGE_PLAYER_SPIN_2]

IMAGE_QBERT_LOSES = pygame.image.load(PATH_IMAGE_QBERT_LOSES)

IMAGE_RED_BALL = pygame.image.load(PATH_IMAGE_RED_BALL)
IMAGE_PURPLE_BALL = pygame.image.load(PATH_IMAGE_PURPLE_BALL)
IMAGE_COILY_LEFT = pygame.image.load(PATH_IMAGE_COILY_LEFT)
IMAGE_COILY_RIGHT = pygame.image.load(PATH_IMAGE_COILY_RIGHT)
IMAGE_COILY_LEFT_JUMP = pygame.image.load(PATH_IMAGE_COILY_LEFT_JUMP)
IMAGE_COILY_RIGHT_JUMP = pygame.image.load(PATH_IMAGE_COILY_RIGHT_JUMP)

IMAGE_DISK = pygame.image.load(PATH_IMAGE_DISK)
IMAGE_SWEAR = pygame.image.load(PATH_IMAGE_SWEAR)

X_CENTER = GAME_WINDOW_WIDTH // 2
Y_CENTER = 120
