import pygame

GAME_WINDOW_WIDTH = 1024
GAME_WINDOW_HEIGHT = 768

CUBE_SIZE = 96

COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 100, 100)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_YELLOW = (255, 255, 51)
COLOR_ORANGE = (255, 178, 80)
COLOR_PURPLE = (255, 102, 255)
COLOR_GRAY = (172, 172, 172)

STANDING = 0
DOWN_LEFT = 1
DOWN_RIGHT = 2
UP_LEFT = 3
UP_RIGHT = 4

START = 0
PLAYING = 1
GAME_OVER = 2

FONT_SIZE = 36

PATH_IMAGE_START_PAGE = 'images/startpage.png'

PATH_IMAGE_PLAYER_LEFT_DOWN = 'images/playerleftdown.png'
PATH_IMAGE_PLAYER_RIGHT_DOWN = 'images/playerrightdown.png'
PATH_IMAGE_PLAYER_LEFT_UP = 'images/playerleftup.png'
PATH_IMAGE_PLAYER_RIGHT_UP = 'images/playerrightup.png'
PATH_IMAGE_PLAYER_LITTLE = 'images/playerlittle.png'

IMAGE_START_PAGE = pygame.image.load(PATH_IMAGE_START_PAGE)

IMAGE_PLAYER_LEFT_DOWN = pygame.image.load(PATH_IMAGE_PLAYER_LEFT_DOWN)
IMAGE_PLAYER_RIGHT_DOWN = pygame.image.load(PATH_IMAGE_PLAYER_RIGHT_DOWN)
IMAGE_PLAYER_LEFT_UP = pygame.image.load(PATH_IMAGE_PLAYER_LEFT_UP)
IMAGE_PLAYER_RIGHT_UP = pygame.image.load(PATH_IMAGE_PLAYER_RIGHT_UP)
IMAGE_PLAYER_LITTLE = pygame.image.load(PATH_IMAGE_PLAYER_LITTLE)

X_CENTER = GAME_WINDOW_WIDTH // 2
Y_CENTER = 120
